### ISSUE TITLE
The Venue

### ISSUE THREAD

**Issue by nikhil3000** [IOSD/HackDTU#10]
In the venue section which is just below the timeline....a grey box appears which is supposed to be map...somehow it got messed up in initial commits..please fix..i have updated the coordinates to DTU's location in js file

**Comment by krishnarai30** [comment]
@dhruvramdev Look into it!

**Comment by dhruvramdev** [comment]
It is a key error. To use google maps on websites , you have to take a key. I have added the placeholder for that. Just issue a key and add that.

https://developers.google.com/maps/documentation/javascript/get-api-key
